### ISSUE TITLE
RoleBindings listed before Roles in template

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#122]
https://github.com/openshift/telemeter/blob/91e1dd6d343b0ca89440bd0776b4719baa532ad4/manifests/server/list.yaml
https://github.com/openshift/telemeter/blob/91e1dd6d343b0ca89440bd0776b4719baa532ad4/manifests/prometheus/list.yaml

Because the RoleBindings are listed before the Roles, our CI fails to apply the rolebinding objects on the first run because the roles are missing.

A workaround is to run the job a second time.

Ideally the Role objects would be listed before the RoleBinding objects in the templates.

**Comment by jfchevrette** [comment]
ksonnet seem to do this specifically because some resources cannot reconcile if listed in the wrong order

https://github.com/ksonnet/ksonnet/blob/8b703db7cf6303ceddb3317a3a24e4b61ad7fc4f/pkg/cluster/sort.go#L95-L148

It does not seem to be possible to do this with jsonnet itself. The roles are in fact already defined prior to the roleBindings in jsonnet/telemeter/prometheus/kubernetes.libsonnet but they end up in a different order in the generated manifests.

**Comment by squat** [comment]
This is because all of the items are defined as fields in a JSON object and key order is never guaranteed for an object. However, if this truly is an issue (my kubectl will happily create a multi-doc yaml file with bindings before roles) we can modify this during the generation of the list. Lists are by definition ordered collections and any ordering we set during its creation will be preserved.
