### ISSUE TITLE
Reader Limit

### ISSUE THREAD

**Issue by mmaier2** [openshift/telemeter#249]
In telemeter-client there is a limit of 200 * 1024 Bytes for the Prometheus reader. Is this just a recommended value or would you rather see that as kind of a hard limit?
Reason is I'm scraping some container_* and kube_* metrics. And those metrics are easily reaching the 200 K limit when the telemeter-client scrapes the Prometheus.

Thanks Markus.

**Comment by squat** [comment]
The client and server both currently enforce limits for the metrics they ingest. On the server side, this is designed to avoid abuse and on the client side this is a conservative setting to ensure that even when additional labels (e.g. clusterID) are added to the shipped metrics that the request does not exceed the server's limit.

In any case, since https://github.com/openshift/telemeter/pull/250 both limits are now configurable via commandline flags (:
