### ISSUE TITLE
documentation for id_code:apiserver_request_error_rate_sum:max

### ISSUE THREAD

**Issue by pranithk** [openshift/telemeter#310]
Hi,
     I was looking for documentation for the metric id_code:apiserver_request_error_rate_sum:max but not able to find it at https://github.com/openshift/telemeter/blob/1512156aa320268c4cfbb3b0b9a3c6eafea36b42/docs/data-collection.md

Please let me know where to find it.

Thanks
Pranith

**Comment by squat** [comment]
Hi Pranith. That document only records metrics collected for telemetry but not every single cluster metric, since not all metrics are sent back to red hat. There metric you mentioned is simply not collected by this project, so we don't have any documentation for it. By the way, the newest, up-to-date version of that doc is now here: https://github.com/openshift/cluster-monitoring-operator/blob/master/Documentation/data-collection.md

**Comment by pranithk** [comment]
@squat Thanks a lot for your response. I asked this question on this project because https://github.com/openshift/telemeter/blob/master/jsonnet/telemeter/rules.libsonnet has this metric listed. Do you happen to know which project has this metric? Thanks again for your time!

**Comment by squat** [comment]
Hi @pranithk ah, that's very different, that is not a singly metric that is collected from the cluster by telemeter, but rather it is a recording rule that we define to speed up queries later. Essentially, the telemeter dashboards have a set of queries that they define and some of them can be very expensive to compute. This particular query is very expensive to compute ad hoc so we choose to pre-compute it using a recording rule that is executed on the backend after ingestion but before querying.

**Comment by pranithk** [comment]
@squat Will it be possible to provide English description of what it does? Something similar to what we have in https://github.com/openshift/cluster-monitoring-operator/blob/master/Documentation/data-collection.md ?
