### ISSUE TITLE
Telemeter server statefulset manifest attempting to create PV claim with invalid name

### ISSUE THREAD

**Issue by jfchevrette** [openshift/telemeter#60]
```
create Claim -telemeter-server-0 for Pod telemeter-server-0 in StatefulSet telemeter-server failed error: PersistentVolumeClaim "-telemeter-server-0" is invalid: [metadata.name: Invalid value: "-telemeter-server-0": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Required value]
```

Possibly related to the empty item here?
https://github.com/openshift/telemeter/blob/f7f7a386279944475d01d28367ea50da1b66a853/manifests/server/list.yaml#L150-L151

**Comment by pbergene** [comment]
@squat would like to try to have this sorted on the morning eu if possible.  I'm traveling, so please sync with @jmelis or @riuvshin if there is anything you need assistance with.   

cc @s-urbaniak

**Comment by s-urbaniak** [comment]
@pbergene @jfchevrette I am having a look at it now

**Comment by s-urbaniak** [comment]
the issue is, that instead of setting empty seq `[]` in the `telemeter-server` statefulSet, we are setting an empty dict `{}`:
https://github.com/openshift/telemeter/blob/d6c33d05d951ca56f1311a9c001f64e7ae0460ba/jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet#L97

Internally, the k8s libsonnet then creates one sequence entry set to empty object. This object is then interpreted by k8s causing the above error.

The resolution is simple: simply set an empty seq `[]` vs. empty dict `{}`. I am submitting a PR now.
